# Generated by Django 5.0.1 on 2024-01-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('views', models.PositiveIntegerField()),
                ('downloads', models.PositiveIntegerField()),
                ('industry', models.CharField(max_length=100)),
                ('runtime', models.PositiveIntegerField()),
                ('IMDb_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('director', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('posted_date', models.DateField()),
            ],
        ),
    ]
